Fix Cat rename signal #2010
chipsalliance/chisel3 pull request #2011
Opened 2021-07-06 11:58 UTC by colin4124

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- bug fix

#### API Impact

No

#### Backend Code Generation Impact

It would rename intermediate node to `hi` or `lo` when use `SeqUtils.asUInt` for a sequence.

#### Desired Merge Strategy

Rebase

#### Release Notes

Fix #2010 
### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2021-07-08 00:57 UTC, jackkoenig requested changes
See my suggestion, also this needs a test.

2021-07-08 00:57 UTC, jackkoenig commented on core/src/main/scala/chisel3/SeqUtils.scala
> +      val hi = if (in_hi.length > 1) wrapper("hi", in_hi) else asUInt(in_hi)
I haven't run this but I don't think it's the right solution. What happens if you do something like:

```scala
class MyModule extends RawModule {
  val a, b, c, d = IO(Input(UInt(8.W)))
  val out = IO(Output(UInt()))
  out := Cat(a + 1.U, b + 1.U, c + 1.U, d + 1.U)
}
```
[Scastie link](https://scastie.scala-lang.org/ARbrm3xURKqbU3KhTCK9Ug)

My guess is that the intermediate wires will no longer get named.

I think the correct solution is:

```suggestion
      val lo = autoNameRecursively("lo") {
         asUInt(in.slice(0, in.length/2))
       }
       val hi = autoNameRecursively("hi") {
         asUInt(in.slice(in.length/2, in.length))
       }
```
Also will need to import `chisel3.plugin. autoNameRecursively`.

`autoNameRecursively` is smart and only names nodes created within the Expression passed to it, so things created previously and passed to it (like stuff from `in` potentially), will not get named.

2021-07-11 08:06 UTC, colin4124 commented
@jackkoenig Thanks for review.

If use chisel3-plugin:

- mill `def scalacPluginIvyDeps = Agg(ivy"edu.berkeley.cs:::chisel3-plugin:3.4.3")`
- sbt `addCompilerPlugin("edu.berkeley.cs" %% "chisel3-plugin" % 3.4.3)`

Both  **orignal version** and **your solution** works well,  are the same.

If not use,

**orignal version** is a bug, and **your solution** generates:

```verilog
module MyModule(
  input  [7:0]  a,
  input  [7:0]  b,
  input  [7:0]  c,
  input  [7:0]  d,
  output [31:0] out
);
  wire [7:0] _out_T_1 = a + 8'h1; // @[Top.scala 8:16]
  wire [7:0] _out_T_3 = b + 8'h1; // @[Top.scala 8:25]
  wire [7:0] _out_T_5 = c + 8'h1; // @[Top.scala 8:34]
  wire [7:0] _out_T_7 = d + 8'h1; // @[Top.scala 8:43]
  wire [15:0] out_lo = {_out_T_5,_out_T_7}; // @[Cat.scala 30:58]
  wire [15:0] out_hi = {_out_T_1,_out_T_3}; // @[Cat.scala 30:58]
  assign out = {out_hi,out_lo}; // @[Cat.scala 30:58]
endmodule
```

So should I take your suggestion, and ensure test well with chisel3-plugin, and leave its result as above without chisel3-plugin?

2021-07-12 20:39 UTC, jackkoenig commented
@colin4124 thanks for continuing to work on this!

> So should I take your suggestion, and ensure test well with chisel3-plugin, and leave its result as above without chisel3-plugin?

Yeah that sounds good to me. I think that's fine it to have worse names without the plugin, and we'll likely deprecate **not** using the plugin in Chisel 3.5 anyway.

2021-07-13 02:27 UTC, sequencer commented
GitHub cache seems to be crazy???
> Run cd z3-z3-4.8.10/build
  cd z3-z3-4.8.10/build
  sudo make install
  z3 --version
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/ea169cc4-2204-4615-b04e-dcfec709bbcb.sh: line 1: cd: z3-z3-4.8.10/build: No such file or directory
Error: Process completed with exit code 1.

2021-07-14 23:22 UTC, merged