Deprecate switch-is
chipsalliance/chisel3 pull request #2069
Opened 2021-08-15 16:54 UTC by sequencer

## tl;dr
`switch-is` is very misleading, users are complaining the bad QoR result from switch.

## Reason to deprecate this API
The implementation of `switch-case` is a cascade `when` block which will return to a cascade `PriorityMux`, lead to a bad QoR of RTL.

Commercial synthesis tool seems being able to statically detect the Mux select signal are mutually exclusive, while `yosys` not being able to generate the parallel look-up-table with this RTL. This may result different circuit in different synthesis tools, since FIRRTL won't check ME among the priorities `Mux`.

High-end Verilog designer will use `parallel_case`, which seems never being able to be provided by Chisel. they always require a parallel PLA(LUT) via case statement, they believe `switch-is` API provide this since it is similar to the Verilog Case Statement, and most of them rightfully use this API.
If they fail to run their circuit to very high frequency, they will blame Chisel PPA...

## Replacement
For the QoR of circuit, I suggest user should migrate to `decode` API to construct PLA or use `Mux1H` explicitly, to achieve a better timing. Neither of them provide a same syntax as `case` statement, but both of them are parallel circuit which provides a better QoR, if users really need a parallel selection logic, they should directly this those API.

## Migration Effort
It is seems to be a tough migration path, however, in UCB-Bar+ChipsAlliance projects, usage of switch is really small(maybe advance users know they should avoid this API. entire `rocket-chip` only uses two `switch` for two times.)
```
hwacha/src/main/scala/smu.scala:139:  switch (state) {
hwacha/src/main/scala/vfu-rpred.scala:71:  switch (state) {
hwacha/src/main/scala/vmu-addr.scala:116:  switch (state) {
hwacha/src/main/scala/vmu-addr.scala:283:  switch (state) {
hwacha/src/main/scala/vmu-addr.scala:380:  switch (state) {
hwacha/src/main/scala/vfu-rfirst.scala:78:  switch (state) {
hwacha/src/main/scala/dcc-fu.scala:163:  switch (state) {
hwacha/src/main/scala/dcc-mem.scala:72:  switch (state) {
hwacha/src/main/scala/dcc-mem.scala:171:  switch (state) {
hwacha/src/main/scala/dcc-mem.scala:335:  switch (state) {
hwacha/src/main/scala/xcpt.scala:111:  switch (state) {
hwacha/src/main/scala/vmu.scala:233:  switch (state) {
hwacha/src/main/scala/vmu-pred.scala:109:  switch (state) {
hwacha/src/main/scala/vmu-pred.scala:271:  switch (state) {
hwacha/src/main/scala/rocc-unit.scala:351:      switch (state) {
firesim/sim/src/main/scala/midasexamples/RiscSRAM.scala:56:  switch(state) {
firesim/sim/midas/src/main/scala/midas/models/dram/LastLevelCache.scala:357:  switch (state) {
firesim/sim/midas/src/main/scala/midas/models/dram/DramCommon.scala:389:    switch(io.selectedCmd) {
firesim/sim/midas/src/main/scala/midas/models/dram/DramCommon.scala:585:  switch (io.cmd) {
firesim/sim/midas/src/main/scala/midas/models/dram/DramCommon.scala:684:    switch(io.selectedCmd) {
firesim/sim/src/main/scala/midasexamples/Risc.scala:43:    switch(op) {
firesim/sim/firesim-lib/src/main/scala/bridges/UARTBridge.scala:119:    switch(txState) {
firesim/sim/firesim-lib/src/main/scala/bridges/UARTBridge.scala:159:    switch(rxState) {
icenet/src/main/scala/Pauser.scala:85:    switch (state) {
rocket-chip/src/main/scala/rocket/PTW.scala:329:  switch (state) {
rocket-chip/src/main/scala/jtag/JtagStateMachine.scala:80:  switch (currState) {
riscv-boom/src/main/scala/exu/rob.scala:802:    switch (rob_state) {
riscv-boom/src/main/scala/exu/rob.scala:832:    switch (rob_state) {
chisel3/src/test/scala/cookbook/FSM.scala:29:  switch (state) {
chisel3/src/test/scala/chiselTests/CompatibilitySpec.scala:169:      switch(op) {
chisel3/src/test/scala/chiselTests/Mem.scala:27:  switch (cnt) {
chisel3/src/test/scala/chiselTests/Mem.scala:65:  switch (cnt) {
chisel3/src/test/scala/chiselTests/Mem.scala:77:  switch (cnt) {
chisel3/src/test/scala/chiselTests/Mem.scala:90:  switch (cnt) {
chisel3/src/test/scala/chiselTests/Mem.scala:107:  switch (cnt) {
chisel3/src/test/scala/chiselTests/Risc.scala:44:    switch(op) {
gemmini/src/main/scala/gemmini/LoadController.scala:125:  switch (control_state) {
gemmini/src/main/scala/gemmini/Transposer.scala:27:  switch(state) {
gemmini/src/main/scala/gemmini/LoopConv.scala:1106:    switch (cmd.bits.inst.funct) {
gemmini/src/main/scala/gemmini/LoopMatmul.scala:705:    switch (cmd.bits.inst.funct) {
gemmini/src/main/scala/gemmini/StoreController.scala:181:  switch (control_state) {
gemmini/src/main/scala/gemmini/TilerFSM.scala:214:  switch (state) {
gemmini/src/main/scala/gemmini/ExecuteController.scala:529:  switch (control_state) {
gemmini/src/main/scala/gemmini/Im2Col.scala:184:  switch(im2col_state){
rocket-dsp-utils/src/main/scala/freechips/rocketchip/jtag2mm/JtagStateMachine.scala:102:    switch(lastState) {
rocket-dsp-utils/src/main/scala/freechips/rocketchip/jtag2mm/JtagToMaster.scala:231:    switch(state) {
rocket-dsp-utils/src/main/scala/freechips/rocketchip/jtag2mm/JtagToMaster.scala:600:    switch(state) {
rocket-dsp-utils/src/main/scala/freechips/rocketchip/jtag2mm/JtagFuzzer.scala:54:  switch(state) {
chisel-testers2/src/test/scala/chiseltest/tests/TestUtils.scala:69:  switch(io.fn) {
sifive-blocks/src/main/scala/devices/spi/SPIMedia.scala:74:  switch (state) {
sifive-blocks/src/main/scala/devices/spi/SPIPhysical.scala:220:      switch (op.fn) {
sifive-blocks/src/main/scala/devices/spi/SPIFlash.scala:97:  switch (state) {
sifive-blocks/src/main/scala/devices/uart/UARTRx.scala:63:  switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SinkC.scala:34:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SinkB.scala:32:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SourceC.scala:47:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SourceA.scala:49:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SourceD.scala:53:    switch (state) {
sifive-blocks/src/main/scala/devices/i2c/I2C.scala:235:      switch (bitState) {
sifive-blocks/src/main/scala/devices/i2c/I2C.scala:237:          switch (bitCmd) {
sifive-blocks/src/main/scala/devices/i2c/I2C.scala:402:    switch (byteState) {
sifive-blocks/src/main/scala/devices/chiplink/SinkA.scala:37:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SinkD.scala:32:    switch (state) {
sifive-blocks/src/main/scala/devices/chiplink/SourceB.scala:44:    switch (state) {
chisel-testers2/src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala:51:    switch(id) {
chisel-testers2/src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala:65:    switch(id) {
chisel-testers2/src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala:83:    switch(id) {
chisel-testers2/src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala:110:    switch(id) {
sha3/src/main/scala/dpath.scala:74:  switch(io.stage){
sha3/src/main/scala/ctrl.scala:186:  switch(rocc_s) {
sha3/src/main/scala/ctrl.scala:216:  switch(mem_s){
sha3/src/main/scala/ctrl.scala:602:  switch(state) {
firrtl/src/main/scala/firrtl/passes/CheckWidths.scala:163:            // Beyond that, switch to an explicit, iterative DFS to avoid stack overflow
firrtl/src/main/scala/firrtl/Driver.scala:192:    StageUtils.dramaticWarning("firrtl.Driver is deprecated since 1.2!\nPlease switch to firrtl.stage.FirrtlMain")
dsptools/src/test/scala/examples/SimpleDspModuleSpec.scala:87:        // you need to switch the backend to Verilator. Note that tests currently need to be dumped in
dsptools/src/main/scala/dsptools/numbers/algebra_types/Order.scala:66:    * Defines an ordering on `A` where all arrows switch direction.
dsptools/src/main/scala/dsptools/numbers/algebra_types/PartialOrder.scala:96:    * Defines a partial order on `A` where all arrows switch direction.
firrtl/src/test/scala/firrtlTests/features/LetterCaseTransformSpec.scala:169:      /* Instance "SuB2" and "SuB3" switch th [...]

2021-08-15 17:20 UTC, kammoh commented
So instead of fixing the QoR issue remove the only available switch/case construct?! To me, as a long time Chisel user, this is a horribly bad idea!

2021-08-15 17:42 UTC, sequencer commented
> So instead of fixing the QoR issue remove the only available switch/case construct?! To me, as a long time Chisel user, this is a horribly bad idea!

This is just a proposal, we should discuss this.
`switch-is` is a good syntax to serve as Verilog Case Statement but it results to a bad QoR. `when` can server just as it is, while providing the syntax `elsewhen` and `otherwise` to indicate user: "THIS IS NOT A PARALLEL CIRCUIT".
For really parallel circuit, I think we should guide users to `decoder` and `Mux1H`, that's the circuit that Verilog Case Statement really generates.

2021-08-15 17:47 UTC, sequencer commented
There was a company using Chisel forbidding user to write `when` and `switch` block to avoid unexpected deep mux, I believe `when` is doing a good job. while the existence of `switch` is decreasing users' confidence to Chisel's PPA.
BTW, FSM implemented by `switch-is` API is also not being able to be inferred by synthesis tool to re-encode the state field.
We should also consider a new FSM API.

2021-08-15 19:39 UTC, ekiwi commented
> So instead of fixing the QoR issue remove the only available switch/case construct?! To me, as a long time Chisel user, this is a horribly bad idea!

I don't think this is actually going to happen. I don't see SiFive adjusting all their internal code to move away from `switch` unless there is a real QoR improvement. However, I do think it would be interesting to explore optimizations in the firrtl compiler as well as potential alternative API that could be provided _along side_ (and not instead of) the `switch` construct.

2021-08-16 01:44 UTC, sequencer commented
If we still keep this API while not providing such optimization passes: maybe we can trade-off: add `switch-linter` to compile option, and print the warning message at runtime, and turn it off by default, this won't affect most users, and can be turned on explicitly for users really care about PPA.

2021-08-16 15:01 UTC, schoeberl commented
When the generated Verilog code from a ```switch``` is as it was in Chisel2, that is way better than using priority-based Muxs.

2021-08-16 15:05 UTC, sequencer commented
> Why do you want to remove switches? Switches should be different from .elsewhen. Switches should be unique cases, but elsewhen has an implicit priority. Switch-generated hardware should use less than priority-based .elsewhen. (I know that this is not anymore the case in Chisel 3, but hopefully might come back at some point. It was the case in Chisel 2).

That's the common misunderstanding, `switch` is parallel, and it provides a better timing/area. Since Chisel3 doesn't provide such "better timing/area", we should warn user not using this API.

2021-08-16 15:09 UTC, sequencer commented
> When the generated Verilog code from a switch is as it was in Chisel2, that is way better than using priority-based Muxs.

Yes, providing Verilog Case Block might be the ultimate way to resole this issue. However it might be too expensive to add switch/case IR. So basically, switch-case will be synthesis to a `PLA` or `Mux1H`, which Chisel has already provided, so guiding user to those API seems more easy.

2021-08-16 15:44 UTC, ekiwi commented
> However it might be too expensive to add switch/case IR.

You probably do not need a special switch/case IR. You could probably get away with doing the exhaustiveness/exclusiveness check for switch with constants in the compiler and then you can annotate the nested muxes for special Verilog emission. You might have to introduce an intermediate IR node, but that wouldn't be too bad. (I would advocate for a `parallel_select` expression instead of adding more statement nodes).

2021-08-16 15:48 UTC, seldridge commented
High level: the SFC should have better code generation for this. It may be worth just waiting for CIRCT to come online as it's already generating better code for `MuxLookup` and will generate better code for arbitrary `switch`/`when` blocks soon.

Also note that in terms of Verilog coding styles for synthesis, an array index seems to be ideal as opposed to case statements. CIRCT is choosing to lower to an array index with a TBD "Verrilog Prettification" pass that will convert array indices into case statements if the user wants that. (There was some discussion about this in the August 11 CIRCT meeting with notes here: https://docs.google.com/document/d/1fOSRdyZR2w75D87yU2Ma9h2-_lEPL4NxvhJGJd-s5pk)

Currently, CIRCT will code gen an array index for `MuxLookup` (or anything that is a mux tree where the condition is a bunch of equality comparisons against the same value).  There's an example of this on https://github.com/llvm/circt/issues/675 for what a seven segment decoder will now produce.

CIRCT's `ExpandWhens` is lowering in an unnecessarily conservative way that is preventing `switch` or `when` from lowering the same way, but there's an issue open about it: https://github.com/llvm/circt/issues/1583. This will be fixed soon and then CIRCT will produce optimal code for `switch`.

tl;dr: this is really a code gen problem where Scala FIRRTL is generating bad code. This can be fixed with pattern matching structure in Scala FIRRTL without needing to expand FIRRTL IR. CIRCT is one PR away from doing this.

2021-08-16 16:18 UTC, sequencer commented
Just learned a lot from CIRCT's meeting notes! I think the last solution is waiting CIRCT to take over!
We'd like to work on the modernize espresso part, making CIRCT being able to use espresso as library to optimize those code automatically. I have been using decoder everywhere to optimize our circuit. I'd like to let CIRCT taking over that.

So instead of deprecating it. can we propose a compiler option to warn user, the generated circuit is not good enough with current Chisel/FIRRTL build. We can turn it off by default, and turn it on explicitly for extreme PPA case as a linter. After we have an optimizing FIRRTL pass or switch to CIRCT finally, we can remove it then.

Actually I just wanna seeking for an answer: "Chisel 3 PPA is worse than SpinalHDL", this rumor is spared in China :(
Most users never tune their circuit :(

For example, a friend of mine did this crazy job(OpenXiangShan/XiangShan#672) in XiangShan, I don't think most of circuit are as good as he is to totally understand how to encode and optimize for timing.

2021-08-16 16:23 UTC, seldridge commented
I played around with this locally and with a quick hack to CIRCT, you will get "good" code emission for either the `switch` or `when` construction. I.e., either of the following:

```scala
class SevenSegmentDecoderSwitch extends RawModule {
  val in = IO(Input(UInt(4.W)))
  val out = IO(Output(UInt(7.W)))
  
  out := 0.U
  switch (in) {
    is("h0".U) { out := "h3F".U }
    is("h1".U) { out := "h06".U }
    is("h2".U) { out := "h5B".U }
    is("h3".U) { out := "h4F".U }
    is("h4".U) { out := "h66".U }
    is("h5".U) { out := "h6D".U }
    is("h6".U) { out := "h7D".U }
    is("h7".U) { out := "h07".U }
    is("h8".U) { out := "h7F".U }
    is("h9".U) { out := "h6F".U }
    is("hA".U) { out := "h77".U }
    is("hb".U) { out := "h7C".U }
    is("hC".U) { out := "h39".U }
    is("hd".U) { out := "h5E".U }
    is("hE".U) { out := "h79".U }
    is("hF".U) { out := "h71".U }
  } 
}
```

```scala
class SevenSegmentDecoderWhen extends RawModule {
  val in = IO(Input(UInt(4.W)))
  val out = IO(Output(UInt(7.W)))
  when (in === "h0".U)       { out := "h3F".U }
    .elsewhen(in === "h1".U) { out := "h06".U }
    .elsewhen(in === "h2".U) { out := "h5B".U }
    .elsewhen(in === "h3".U) { out := "h4F".U }
    .elsewhen(in === "h4".U) { out := "h66".U }
    .elsewhen(in === "h5".U) { out := "h6D".U }
    .elsewhen(in === "h6".U) { out := "h7D".U }
    .elsewhen(in === "h7".U) { out := "h07".U }
    .elsewhen(in === "h8".U) { out := "h7F".U }
    .elsewhen(in === "h9".U) { out := "h6F".U }
    .elsewhen(in === "hA".U) { out := "h77".U }
    .elsewhen(in === "hb".U) { out := "h7C".U }
    .elsewhen(in === "hC".U) { out := "h39".U }
    .elsewhen(in === "hd".U) { out := "h5E".U }
    .elsewhen(in === "hE".U) { out := "h79".U }
    .elsewhen(in === "hF".U) { out := "h71".U }
    .otherwise               { out := 0.U     }
}
```

Will produce:

```verilog
module SevenSegmentDecoderSwitch(
  input  [3:0] in,
  output [6:0] out);

  wire [15:0][6:0] _tmp = {{7'h3F}, {7'h6}, {7'h5B}, {7'h4F}, {7'h66}, {7'h6D}, {7'h7D}, {7'h7}, {7'h7F}, {7'h6F}, {7'h77}, {7'h7C}, {7'h39}, {7'h5E}, {7'h79}, {7'h71}};
  assign out = _tmp[in];
endmodule
```

The real problem is that we're not ready for load bearing users. 😄  We're getting there, though. This type of code emission can be done in Scala FIRRTL, it just needs somebody to drive it and get a patch together for Scala FIRRTL's Verilog emitter to recognize this and emit it as above or using case statements.

2021-08-16 16:27 UTC, sequencer commented
BTW, wondering the PPA result vs [decoder API]( https://github.com/chipsalliance/chisel3/blob/1ceb974c55c6785c21ab3934fa750ade0702e276/src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala#L99-L115)

2021-08-16 17:33 UTC, jackkoenig requested changes
I think it's clear that we shouldn't deprecate this and should instead wait for better code gen via CIRCT. If someone wants to, it's probably not *that* bad to add improved emission for switch-is (and dynamic indexing) via pattern matching, but that needs someone willing to spend the time.

2021-08-16 17:38 UTC, closed without merging

2021-08-16 19:11 UTC, seldridge commented
FYI, thanks to @youngar, there's a fix into CIRCT that does the array emission above for both `switch` and well-structured `when`: https://github.com/llvm/circt/issues/1583 🎊