Update Issue template
chipsalliance/chisel3 pull request #2237
Opened 2021-11-04 00:08 UTC by Burnleydev1

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

performance improvement       

#### API Impact
No impact

#### Backend Code Generation Impact
No impact

#### Desired Merge Strategy
Squash

#### Release Notes
Update Issue template

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2021-11-04 00:21 UTC, mwachs5 commented
Fixes #2236

2021-11-04 00:22 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
can we not keep the content from our old Issue template? What about this one makes it a "new" one vs the old one?

2021-11-04 00:25 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Okay I will remove it, I was thinking it will be relevant information for someone creating an issue.

2021-11-04 00:27 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, gitter, [Scastie](https://scastie.scala-lang.org/KtzZQ3nFTea9KoNh0
what about this one, should I remove it too?

2021-11-04 00:59 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Okay @mwachs5, I will be waiting on your review to improve this PR, thank you.
And I also wish to ask how documentions and

2021-11-04 06:02 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Sorry @mwachs5, I thought this was rhetorical question to follow as to why I added content from the old issue template.
The main difference between this new template and the old one is that when you click on `new issue, you get to chose between the possible issues (bug fix, feature request), and then each issue type has its own template on how to fill it.

2021-11-04 06:03 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Sorry for replying to this late.

2021-11-04 06:17 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
sure... can we keep the basic questions the same as they currently are? At least for the issue one?

2021-11-04 06:18 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Version [e.g. 22]
```suggestion
```

We definitely don't need this

2021-11-04 06:18 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots to help explain your problem.
```suggestion
```

I don't think we want to encourage screenshots

2021-11-04 06:21 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
![Screenshot from 2021-11-03 23-13-23](https://user-images.githubusercontent.com/81782853/140267204-4e71337b-8608-4a76-b77c-137edc29f7f5.png)


This is the window that will pop up when you click the `new issue` button,
from there after choosing your issue type,

2021-11-04 06:21 UTC, mwachs5 commented
I guess I would suggest taking most of the content from the current one, and getting rid of the "if the current behavior is a bug..." wording for the Bug one:

```
<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
<!--
This repository's issues are reserved for feature requests and bug reports.
Please select the item best describing the issue in each category and delete the other items.
-->
<!-- choose all that apply -->
**Type of issue**: bug report

<!-- choose one -->
**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Other information**
 <!-- include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, gitter, Scastie (https://scastie.scala-lang.org/KtzZQ3nFTea9KoNh0tRqtg) -->

**Please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**
<!--    (examples)
    - version: `3.4-SNAPSHOT`
    - OS: `Linux knight 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
-->

**What is the use case for changing the behavior?**
```

2021-11-04 06:28 UTC, Burnleydev1 commented
> I guess I would suggest taking most of the content from the current one, and getting rid of the "if the current behavior is a bug..." wording for the Bug one:
> 
> ```
> <!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
> <!--
> This repository's issues are reserved for feature requests and bug reports.
> Please select the item best describing the issue in each category and delete the other items.
> -->
> <!-- choose all that apply -->
> **Type of issue**: bug report
> 
> <!-- choose one -->
> **Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown
> 
> **Other information**
>  <!-- include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, gitter, Scastie (https://scastie.scala-lang.org/KtzZQ3nFTea9KoNh0tRqtg) -->
> 
> **Please provide the steps to reproduce the problem:**
> 
> **What is the current behavior?**
> 
> **What is the expected behavior?**
> 
> **Please tell us about your environment:**
> <!--    (examples)
>     - version: `3.4-SNAPSHOT`
>     - OS: `Linux knight 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
> -->
> 
> **What is the use case for changing the behavior?**
> ```

Okay I've done that, That means we will allow the feature requests as it is?

2021-11-04 06:32 UTC, Burnleydev1 commented
> I guess I would suggest taking most of the content from the current one, and getting rid of the "if the current behavior is a bug..." wording for the Bug one:
> 
> ```
> <!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
> <!--
> This repository's issues are reserved for feature requests and bug reports.
> Please select the item best describing the issue in each category and delete the other items.
> -->
> <!-- choose all that apply -->
> **Type of issue**: bug report
> 
> <!-- choose one -->
> **Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown
> 
> **Other information**
>  <!-- include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, gitter, Scastie (https://scastie.scala-lang.org/KtzZQ3nFTea9KoNh0tRqtg) -->
> 
> **Please provide the steps to reproduce the problem:**
> 
> **What is the current behavior?**
> 
> **What is the expected behavior?**
> 
> **Please tell us about your environment:**
> <!--    (examples)
>     - version: `3.4-SNAPSHOT`
>     - OS: `Linux knight 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
> -->
> 
> **What is the use case for changing the behavior?**
> ```

I agree too because what github wanted was for us to change the format to creating a new issue, and not to change the the template it itself.

2021-11-04 06:33 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Yes we can.

2021-11-04 17:34 UTC, Burnleydev1 commented
Hello @mwachs5, @debs-sifive, please I need help filling this.
`
Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later. `

2021-11-04 18:11 UTC, Burnleydev1 commented
Hello @mwachs5, please what next can I do to improve on this template?

2021-11-04 18:12 UTC, mwachs5 reviewed
@chick , @jackkoenig is there any impact from this on the automated release process?

2021-11-06 01:52 UTC, Burnleydev1 commented
> > I guess I would suggest taking most of the content from the current one, and getting rid of the "if the current behavior is a bug..." wording for the Bug one:
> > ```
> > <!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
> > <!--
> > This repository's issues are reserved for feature requests and bug reports.
> > Please select the item best describing the issue in each category and delete the other items.
> > -->
> > <!-- choose all that apply -->
> > **Type of issue**: bug report
> > 
> > <!-- choose one -->
> > **Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown
> > 
> > **Other information**
> >  <!-- include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, gitter, Scastie (https://scastie.scala-lang.org/KtzZQ3nFTea9KoNh0tRqtg) -->
> > 
> > **Please provide the steps to reproduce the problem:**
> > 
> > **What is the current behavior?**
> > 
> > **What is the expected behavior?**
> > 
> > **Please tell us about your environment:**
> > <!--    (examples)
> >     - version: `3.4-SNAPSHOT`
> >     - OS: `Linux knight 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
> > -->
> > 
> > **What is the use case for changing the behavior?**
> > ```
> 
> I agree too because I think what github wanted was for us to change the format to creating a new issue, and not to change the the template it itself.

Sorry, I meant not to change the content of the template.

2022-04-18 14:47 UTC, Burnleydev1 commented
Hi @mwachs5, My laptops screen was bad but I have fixed it now and would like a review for this PR.

2022-04-18 15:32 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
Can you copy this "Note" text also to the feature_request.md ?

2022-04-18 15:33 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- choose all that apply -->
```suggestion
```

We don't need that instruction since it's now just a Bug Report

2022-04-18 15:34 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown
```suggestion
```

This never made sense for bug report *or* feature request

2022-04-18 15:35 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Other information**
Can we put this "Other Information" at the end (after "please tell us about your environment)? Since we already ask for what we really care about, it seems like "other" should go at the end.

2022-04-18 15:56 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Other information**
Yes I can do that

2022-04-18 15:57 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
Yes I can

2022-04-18 16:03 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
I think it is there already.
I might be seeing it differently.

2022-04-18 16:08 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
hm, I don't see it, be sure to commit and push your changes to the correct branch?

2022-04-18 16:09 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
<img width="809" alt="Screen Shot 2022-04-18 at 9 09 05 AM" src="https://user-images.githubusercontent.com/17858596/163837350-57bd468b-bbe3-4465-acfc-96b57fac748d.png">

2022-04-18 16:14 UTC, Burnleydev1 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Note: for support questions, you are strongly advised to use [Stack Overflow](https://stackoverflow.com/questions/tagged/chisel). -->
I'm sorry, I was still looking at the bug_report file. But I have added it now to the feature_request.md file

2022-04-18 16:28 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
```suggestion
**Type of issue**: bug report

**Please provide the steps to reproduce the problem:**

```

remove unnecessary spaces

2022-04-18 20:08 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Type of issue**: bug report
```suggestion
**Type of issue**: Bug Report
```

2022-04-18 20:08 UTC, mwachs5 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +**Type of issue**: Feature request
```suggestion
**Type of issue**: Feature Request
```

2022-04-18 22:50 UTC, mwachs5 commented
LGTM! Thanks! Please test it out once it merges to make sure that it works the way we expect and open a revert PR if we broke everything 😬

2022-04-18 22:50 UTC, mwachs5 requested changes
oh wait! one more thing. Can you delete the old ISSUE_TEMPLATE?

2022-06-18 08:30 UTC, Burnleydev1 commented
Hello @mwachs5  this is a [pr](#2589) deleting the old issue template

2022-06-21 16:25 UTC, mwachs5 commented
@Burnleydev1 Can you just delete the ISSUE_TEMPLATE.md file on this PR so that the change is atomic?

2022-06-27 21:25 UTC, mwachs5 approved these changes

2022-06-27 22:04 UTC, merged