ShiftRegister() and ShiftRegisters() now has a flatten option
chipsalliance/chisel3 pull request #2297
Opened 2021-12-09 07:01 UTC by oharboe

flattening is default on, when off a module is used to implement
the shift registers.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

#### API Impact

#### Backend Code Generation Impact

#### Desired Merge Strategy

#### Release Notes

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2021-12-09 08:19 UTC, sequencer commented
I don't object adding `Module` to `ShiftRegister(s)`, this is good for post synthesis flow, since PnR may need take additional care to this.
I personally think there are two method to do so:
1. adding a module and provide a `inline` option, but default to be `false` to avoid affecting other users. add `firrtl.passes.InlineAnnotation` to the correspond instance if true.
2. rather than adding a new `Module`, you can also use `chisel3.util.experimental.group` to gather register into a Module.

2021-12-09 13:22 UTC, mwachs5 requested changes
You will need to write tests

2021-12-09 13:22 UTC, mwachs5 commented on src/main/scala/chisel3/util/Reg.scala
> +        val in = IO(Input(UInt()))
This should not be an IO

2021-12-09 13:22 UTC, mwachs5 commented on src/main/scala/chisel3/util/Reg.scala
> +      class ShiftRegisters extends Module {
Can you call this ShiftRegister or ShiftReg? The "s" is implied

2021-12-09 13:22 UTC, mwachs5 commented on src/main/scala/chisel3/util/Reg.scala
> +  def apply[T <: Data](in: T, n: Int, en: Bool = true.B, flatten: Boolean = true): T = ShiftRegisters(in, n, en, flatten).lastOption.getOrElse(in)
I think "inline" is a better name for this parameter, it's more industry standard

2021-12-09 13:22 UTC, mwachs5 commented on src/main/scala/chisel3/util/Reg.scala
> +        val resetData = IO(Input(Bool()))
Doesn't this need en as an input too?

2021-12-09 13:22 UTC, mwachs5 commented on src/main/scala/chisel3/util/Reg.scala
> +        val in = IO(Input(UInt()))
Doesn't this need en as an input too?

2021-12-09 13:24 UTC, mwachs5 commented
I also like the @sequencer suggestion of the inlineAnnotation, but we should look at the difference in the output from the current solution to one using that to see if the changes are acceptable

2021-12-09 14:07 UTC, oharboe commented
> You will need to write tests

Yep. This is just for discussion for now though.

I want to know how to handle indexing of vectors, where I think it would be similarly helpful to control flattening.

2021-12-13 09:53 UTC, oharboe commented
This needs a more cross-cutting solution. In the spirit of this pull request, there should be a way to control flattening of  Vec() index access. Vec() access for something like Vec(16, UInt(64.W)) generates a giant fog of logic and should be representable as a module.

2021-12-13 09:53 UTC, closed without merging