Add lexical scope checks to Assert, Assume and Printf
chipsalliance/chisel3 pull request #2706
Opened 2022-08-25 20:44 UTC by adkian-sifive

When passing a `Printable` to `assert`, `assume` or `printf`, the scope of where the `Printable` was constructed should be the same as where it is being referenced. This is currently not checked, which makes it possible to construct cases where invalid FIRRTL is generated. Specifically, if the `Printable` is constructed in an inner module and referenced from an outer module, the resulting FIRRTL can have references to objects like wires or temporaries that are local to the inner module. 

For example, the following snippet

```
class InnerPrintable extends Module {
  val in = IO(Input(UInt(8.W)))
  val out = IO(Output(UInt(8.W)))

  val w = Wire(UInt(8.W))
  w := 255.U
  val p = p"$w"

  out := in
}

ChiselStage.emitChirrtl { 
  new Module {
    val mod = Module(new InnerPrintable)
    printf(mod.p)
  }
}
```
outputs the problematic FIRRTL `printf`

```
  module InnerPrintable:
    input clock : Clock
    ...

    wire w : UInt<8>
    w <= UInt<8>("hff")
    ...

module Outer_Anon :
    input clock : Clock
    ...

    node _T = bits(reset, 0, 0)
    node _T_1 = eq(_T, UInt<1>("h0"))
    when _T_1 : 
      printf(clock, UInt<1>("h1"), "%d", w) : printf
```
where the wire `w` internal to `InnerPrintable` is being accessed outside of its scope.

This PR adds checks to `assert`, `assume` and `printf` to ensure that the Builder scopes at `Printable` construction and reference are the same.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

  - bug fix                            

#### API Impact

N/A

#### Backend Code Generation Impact

Printfs, asserts and assumes will not be present in the generated Verilog if the Printable scopes are invalid.

#### Desired Merge Strategy

  - Squash: The PR will be squashed and merged (choose this if you have no preference. 

#### Release Notes

Printables (and other objects?) used in printf, assert and assume can now only be referenced in the scopes in which they were constructed

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.4.x`, [small] API extension: `3.5.x`, API modification or big change: `3.6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

2022-09-02 19:21 UTC, jackkoenig requested changes
This is a great idea but the implementation needs to be more about checking the lexical scope of the individual Data within a `Printable` rather than of the `Printable` objects themselves.

2022-09-02 19:21 UTC, jackkoenig commented on core/src/main/scala/chisel3/Printable.scala
> +  val context = internal.Builder.currentModule
The context/lexical scope we need to check is not a property of the `Printable` object, rather it's a property of the `Data` boxed by various `Printables` (eg. `Decimal`). Thus `Printable` itself should not be capturing the Module in which it was created. Furthermore, lexical scope also needs to take `when` scoping into account, see this example Scastie (https://scastie.scala-lang.org/yJB6k07dSm6rTian91M1rA)

As a straw man, I think what you want to do is have a [package private] method (maybe `def checkLexicalScope(moduleContext: RawModule, whenContext: Option[WhenContext]): Unit`) that recurses through the `Printable` structure and checks the lexical scope of each `Data`, reporting an error if the scope is violated.

2022-09-14 22:09 UTC, jackkoenig commented on core/src/main/scala/chisel3/Printable.scala
> +  val context = internal.Builder.currentModule
Also I think this is unused now right?

2022-09-14 22:14 UTC, adkian-sifive commented on core/src/main/scala/chisel3/VerificationStatement.scala
> +  def checkScope(message: Option[Printable]): Unit = {
If i just take it out the printables with the `message` field None like `p"ok"` error with None.get - I'd have to update the callsites as `checkScope(message.getOrElse(None))` or something which seems more verbose?

2022-09-21 00:48 UTC, jackkoenig commented on core/src/main/scala/chisel3/VerificationStatement.scala
> +  def checkScope(message: Option[Printable]): Unit = {
You could make the callsite just be `message.foreach(checkScope(_))`

2022-09-28 22:11 UTC, jackkoenig commented on src/test/scala/chiselTests/Assert.scala
> +}
```suggestion
class AssertPrintablePortScope extends BasicTester {
  val mod = Module(new PrintableScopeTester)
  assert(1.U === 2.U, mod.printablePort)
  stop()
}
```
`BasicTester` **is** a Module, it's intended to be a Chisel TestBench testing Chisel inside of it. If you run `elaborate` in side of it, you're doing a separate Chisel elaboration that throws away whatever you built. Thus these tests aren't testing what you think they are unless you just actually instantiate the stuff you want normally as I've shown in this suggestion.

Please fix the tests below as well.

2022-09-29 18:38 UTC, jackkoenig approved these changes
LGTM!

2022-09-29 18:38 UTC, merged